[package]
name = "open_ref_cycles_weak"
version = "0.1.0"
authors = ["dart"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
