[package]
name = "open_advanced_type1_aliases"
version = "0.1.0"
authors = ["coolsync <coolsyn@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
